/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  11155420: {
    FileVault: {
      address: "0x392e5a354a139fE0001A2007bE2E4308c275be94",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileHash",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "AccessGranted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileHash",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "AccessRevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "string",
              name: "cid",
              type: "string",
            },
            {
              indexed: true,
              internalType: "address",
              name: "uploader",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address[]",
              name: "allowedUsers",
              type: "address[]",
            },
          ],
          name: "FileUploaded",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileHash",
              type: "bytes32",
            },
          ],
          name: "getCid",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileHash",
              type: "bytes32",
            },
          ],
          name: "getUploader",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileHash",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "grantAccess",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileHash",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "isAuthorized",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileHash",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "revokeAccess",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "cid",
              type: "string",
            },
            {
              internalType: "address[]",
              name: "allowedUsers",
              type: "address[]",
            },
          ],
          name: "storeFileHash",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 36147590,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
